### ISSUE TITLE
Introduction Markdown Page - improper data types 

### ISSUE THREAD

**Issue by davidmdrake** [koalaverse/anomalyDetection#1]
In security_logs data frame,  Src_Port and Dst_Port are integers and get summed when you create your state vector creation. "host (website) addresses and port numbers are necessarily part of the underlying TCP/IP protocols", so ports should be of character data type just like IP address. 

This changes some of your results listed out in introduction.Rmd. Still after changing the data types, this data's boxplot calculations after multivariate analysis still show interesting outliers! 

+1 for this package from me.

**Comment by bradleyboehmke** [comment]
Delayed response.  Being revised and pushed out on the next version update which will be over the next few days.  Thanks for point it out!
